UQcsse3200/2024-studio-2

- source/core/src/main/com/csse3200/game/inventory/items/ConsumableItem.java
- source/core/src/main/com/csse3200/game/inventory/items/exceptions/ConsumedException.java
- source/core/src/test/com/csse3200/game/inventory/items/ConsumableItemTest.java
Applying changes from issue #27  for feature #3
> Created abstract classes for ConsumableItem #3 #27

- source/core/src/main/com/csse3200/game/inventory/Inventory.java
- source/core/src/main/com/csse3200/game/inventory/InventoryInterface.java
- source/core/src/test/com/csse3200/game/inventory/InventoryTest.java
This is intended as the first implementation of an inventory (#19 ) for feature #3  - it implements an interface which can hopefully later be abstracted to represent all in-game containers and (fingers crossed) thoroughly tests the initial inventory implementation.
> Version 1 of Inventory (#19) for #3

- source/core/src/main/com/csse3200/game/inventory/Inventory.java
- source/core/src/main/com/csse3200/game/inventory/items/AbstractItem.java
- source/core/src/test/com/csse3200/game/inventory/items/AbstractItemTest.java
> Implemented item texture

- .gitignore
- source/core/src/main/com/csse3200/game/files/FileLoader.java
- source/core/src/main/com/csse3200/game/gamestate/Achievements.java
- source/core/src/main/com/csse3200/game/gamestate/GameState.java
- source/core/src/main/com/csse3200/game/gamestate/SaveHandler.java
- source/core/src/main/com/csse3200/game/gamestate/data/WorldState.java
- source/core/src/test/com/csse3200/game/gamestate/EnvironmentVariablesTest.java
- source/core/src/test/com/csse3200/game/gamestate/GameStateTest.java
- source/core/src/test/com/csse3200/game/gamestate/SaveHandlerTest.java
Uses JSON to save and load game state/achievements. See wiki (https://github.com/UQcsse3200/2024-studio-2/wiki/Game-State-Saves) for functionality details.
Closes #15 .
> Team 5: Added JSON saving and loading functionality

- source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
- source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
- source/core/src/main/com/csse3200/game/components/CameraComponent.java
- source/core/src/main/com/csse3200/game/components/CameraZoomComponent.java
- source/core/src/main/com/csse3200/game/components/animal/AnimalSelectionActions.java
- source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
- source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
- source/core/src/main/com/csse3200/game/rendering/Renderer.java
- source/core/src/test/com/csse3200/game/components/CameraComponentTest.java
- source/core/src/test/com/csse3200/game/components/CameraZoomComponentTest.java
- source/core/src/test/com/csse3200/game/components/animal/AnimalSelectionActionsTest.java
This commit adds a **player camera** feature which makes the game camera follow the player character as they move around the world. By scrolling the mouse wheel up or down the camera zooms in or out on the player, respectively.
This commit also includes unit tests for the new player camera feature as well as some unit tests for other team 1 features that are already in main.
> Player Camera and Unit Tests

- source/core/src/main/com/csse3200/game/components/animal/AnimalSelectionActions.java
> Added comments

- saves/quests.json
- source/core/src/main/com/csse3200/game/GdxGame.java
- source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
- source/core/src/main/com/csse3200/game/components/combat/CombatExitDisplay.java
- source/core/src/main/com/csse3200/game/components/gameover/GameOverActions.java
- source/core/src/main/com/csse3200/game/components/gameover/GameOverLoseDisplay.java
- source/core/src/main/com/csse3200/game/components/gameover/GameOverWinDisplay.java
- source/core/src/main/com/csse3200/game/components/tasks/WanderTask.java
- source/core/src/main/com/csse3200/game/screens/BossCutsceneScreen.java
- source/core/src/main/com/csse3200/game/screens/GameOverLoseScreen.java
- source/core/src/main/com/csse3200/game/screens/GameOverWinScreen.java
Have fixed space bar bug which crashed the game on spawn of Kanga Boss. Also re-implemented returning to combat on combat win. Combat loss still takes you to game over screen where you must exit the game.
The bug persists where the stats for combat do not load if the boss has been spawned. I will make an issue for this.
> Sprint1 space bug

- source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
- source/core/src/main/com/csse3200/game/components/combat/move/CombatMoveComponent.java
- Updated to align more closely to new combat system spec:
- Changed COUNTER move to SLEEP
- Significantly changed sequencing of move performance
- General updates and tidying up (removed redundant function)
- Move execution is NOT implemented yet, rather just comments on a proposed way of how it could be done
Emphasis on PROPOSED - open to feedback and happy for you to Request Changes.
Questions/things to consider:
- Can we just feed the CombatStatsComponents (which we already have in CombatManager) directly to each CombatMove class rather than passing in the entity and extracting the CombatStatsComponent?
- Is stamina something we should store in CombatStatsComponent or locally in the CombatManager class (as something like PlayerStamina = playerStats.getStartingStamina)? It seems to be …
> Proposed Update to Combat Logic Framework

- source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
- source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
- source/core/src/main/com/csse3200/game/areas/terrain/TerrainLoader.java
Fixed #151 by correctly assigning components and removing static usage.
> Fixed terrain not loading after first game.

- saves/quests.json
- source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
- source/core/src/main/com/csse3200/game/components/combat/CombatButtonDisplay.java
Resized buttons and aligned them with the updated combat system. Additionally, cleaned up code by refining comments and removing unnecessary clutter for better readability .
> updated combat buttons to match current combat system.

- source/core/assets/configs/NPCs.json
- source/core/src/main/com/csse3200/game/ui/DialogueBox.java
- source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
Integrates birdie dash to the magpie npc in the main game. Very small pull request  Will close #182
> Magpie birdie dash minigame integration

- source/core/src/main/com/csse3200/game/inventory/items/lootbox/LootBox.java
- source/core/src/main/com/csse3200/game/inventory/items/lootbox/configs/BaseLootTable.java
- source/core/src/main/com/csse3200/game/inventory/items/lootbox/configs/LootItemConfig.java
- source/core/src/main/com/csse3200/game/inventory/items/lootbox/rarities/EarlyGameLootBox.java
- source/core/src/main/com/csse3200/game/inventory/items/lootbox/rarities/LateGameLootBox.java
- source/core/src/main/com/csse3200/game/inventory/items/lootbox/rarities/MediumGameLootBox.java
- source/core/src/test/com/csse3200/game/inventory/items/lootbox/LootBoxTest.java
Added further testing of loot boxes (for now this is just testing initialisation, but in future this can be extended to proper testing).
> Loot box testing

- source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
> fixed movement issue

- source/core/src/main/com/csse3200/game/components/tasks/AvoidTask.java
- source/core/src/main/com/csse3200/game/ui/dialoguebox/DialogueBox.java
Updated JavaDoc from failed test
> Updated JavaDoc

- source/core/assets/configs/ForestGameAreaConfigs/forestTiles.json
- source/core/assets/configs/ForestGameAreaConfigs/textures.json
- source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/ForestTileConfig.java
- source/core/src/main/com/csse3200/game/areas/terrain/TerrainChunk.java
- source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
- source/core/src/test/com/csse3200/game/areas/terrain/TerrainChunkTest.java
Added function to record/return the number of total tile type in the chunk.
> Chunk tile count  function  

- source/core/src/main/com/csse3200/game/components/inventory/InventoryComponent.java
- source/core/src/main/com/csse3200/game/components/inventory/PlayerInventoryDisplay.java
- source/core/src/main/com/csse3200/game/inventory/Inventory.java
- source/core/src/main/com/csse3200/game/inventory/InventoryInterface.java
- source/core/src/test/com/csse3200/game/inventory/InventoryTest.java
This branch contains the code for adding subscript to each item in inventory and hotbar and the drag and drop feature. The drag and drop feature is implemented between the inventory and hotbar and is an essential part of the user game experience.
Fixes / Closes # (issue)
There are only 2 features included in this request/
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> Drag And Drop and Subscripts Added

- source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
- source/core/src/main/com/csse3200/game/components/quests/AchievementDisplay.java
- source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
Added the achievements button back into the main menu, setup button for clearing achievements (not yet functional)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> 5 achievements 3

- source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
- source/core/src/main/com/csse3200/game/entities/configs/BaseEnemyEntityConfig.java
Just changed a comment to fix javadoc error on main
> fixed javadoc error

- source/core/src/main/com/csse3200/game/components/combat/CombatButtonDisplay.java
> [Team 10] Hovering Mouse over combat move provides additional info

- source/core/src/main/com/csse3200/game/areas/CombatArea.java
- source/core/src/main/com/csse3200/game/components/animal/AirAnimalSelectionDisplay.java
- source/core/src/main/com/csse3200/game/components/animal/AnimalRouletteActions.java
- source/core/src/main/com/csse3200/game/components/animal/AnimalRouletteDisplay.java
- source/core/src/main/com/csse3200/game/components/animal/AnimalSelectionActions.java
- source/core/src/main/com/csse3200/game/components/animal/AnimalSelectionDisplay.java
- source/core/src/main/com/csse3200/game/components/animal/LandAnimalSelectionDisplay.java
- source/core/src/main/com/csse3200/game/components/animal/WaterAnimalSelectionDisplay.java
- source/core/src/main/com/csse3200/game/screens/AirAnimalSelectionScreen.java
- source/core/src/main/com/csse3200/game/screens/AnimalRouletteScreen.java
- source/core/src/main/com/csse3200/game/screens/AnimalSelectionScreen.java
- source/core/src/main/com/csse3200/game/screens/LandAnimalSelectionScreen.java
- source/core/src/main/com/csse3200/game/screens/WaterAnimalSelectionScreen.java
- source/core/src/main/com/csse3200/game/ui/PopUpDialogBox/PopupDialogBox.java
- source/core/src/test/com/csse3200/game/components/animal/AnimalSelectionActionsTest.java
Reverts UQcsse3200/2024-studio-2#478
> Revert "created roulette feature for air land and water"

- source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
- source/core/src/main/com/csse3200/game/areas/MiniMapDisplay.java
- source/core/src/test/com/csse3200/game/areas/MiniMapDisplayTest.java
- source/core/src/test/com/csse3200/game/components/login/PlayFabTest.java
Fixed Minimap indexing issue from https://github.com/UQcsse3200/2024-studio-2/pull/431
> 6 start settings

- source/core/src/main/com/csse3200/game/overlays/PauseDisplay.java
Added a simple save button on the PauseScreen that will save the game's current state (It's pretty simple, but didn't want to put it into another pr with different direction)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> Added new save button on the pause menu

- source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
- source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java
- source/core/src/main/com/csse3200/game/entities/configs/BaseEnemyEntityConfig.java
- source/core/src/main/com/csse3200/game/entities/configs/BaseEntityConfig.java
- source/core/src/main/com/csse3200/game/entities/configs/BaseFriendlyEntityConfig.java
- source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
- source/core/src/main/com/csse3200/game/ui/dialoguebox/KeyboardDialogueBoxInputComponent.java
- source/core/src/test/com/csse3200/game/components/tasks/PauseTaskTest.java
- source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
This pull request aims to remove issues that sonar cloud has with the code and add JavaDoc strings to all methods apart of team 4's code that is missing it. I believe no functional changes have been made, and everything should work as before. Closes (#533).
Nothing functional should be changed, but I ran the game and ensured that the gameplay remained as expected as well as building the code.
> [Team 4's Code Clean Up]

- source/core/src/main/com/csse3200/game/GdxGame.java
- source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
- source/core/src/main/com/csse3200/game/areas/GameArea.java
- source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
- source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
- source/core/src/main/com/csse3200/game/components/inventory/PlayerInventoryDisplay.java
- source/core/src/main/com/csse3200/game/components/lootboxview/LootBoxOverlayComponent.java
- source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
- source/core/src/main/com/csse3200/game/inventory/Inventory.java
- source/core/src/main/com/csse3200/game/inventory/items/AbstractItem.java
- source/core/src/main/com/csse3200/game/inventory/items/ItemUsageContext.java
- source/core/src/main/com/csse3200/game/inventory/items/TimedUseItem.java
- source/core/src/main/com/csse3200/game/inventory/items/food/AbstractFood.java
- source/core/src/main/com/csse3200/game/inventory/items/food/Foods.java
- source/core/src/main/com/csse3200/game/inventory/items/lootbox/UniversalLootBox.java
- source/core/src/main/com/csse3200/game/inventory/items/lootbox/configs/BaseLootTable.java
- source/core/src/main/com/csse3200/game/inventory/items/lootbox/configs/LootItemConfig.java
- source/core/src/test/com/csse3200/game/inventory/items/FoodItemTest.java
Fixes code smells, tests and javadocs for team 3 code. A minor amount of code for other teams has been changed (mainly to do with unused code or changing random number generators to use thread-safe versions). 
This contributes to ticket #538 - although is not yet sufficient to close it (more testing and code smells need to be addressed).
There should be no functionality changes at all.
No functionality changes intended - all current unit tests pass. Basic game play has also been completed and on the surface does not appear to affect any functionality.
> Code Clean Up [Team 3]

- source/core/src/test/com/csse3200/game/components/CameraZoomComponentTest.java
- source/core/src/test/com/csse3200/game/components/animal/AnimalRouletteDisplayTest.java
- source/core/src/test/com/csse3200/game/components/audio/DogSoundPlayerTest.java
- source/core/src/test/com/csse3200/game/components/chatbot/ChatbotServiceTest.java
- source/core/src/test/com/csse3200/game/components/combat/move/SpecialAirMoveTest.java
- source/core/src/test/com/csse3200/game/components/combat/move/SpecialKangaMoveTest.java
- source/core/src/test/com/csse3200/game/components/combat/move/SpecialMoveTest.java
- source/core/src/test/com/csse3200/game/components/combat/move/SpecialWaterMoveTest.java
- source/core/src/test/com/csse3200/game/components/combat/quicktimeevent/QuickTimeEventTest.java
- source/core/src/test/com/csse3200/game/components/inventory/CombatInventoryDisplayTest.java
- source/core/src/test/com/csse3200/game/components/player/PlayerInventoryDisplayTest.java
- source/core/src/test/com/csse3200/game/components/stats/StatsDisplayTest.java
- source/core/src/test/com/csse3200/game/components/tasks/PauseTaskTest.java
- source/core/src/test/com/csse3200/game/inventory/InventoryTest.java
- source/core/src/test/com/csse3200/game/minigames/MiniGameScoresTest.java
- source/core/src/test/com/csse3200/game/minigames/birdieDash/entities/BirdTest.java
- source/core/src/test/com/csse3200/game/minigames/birdieDash/entities/CoinTest.java
- source/core/src/test/com/csse3200/game/minigames/birdieDash/entities/PipeTest.java
- source/core/src/test/com/csse3200/game/minigames/birdieDash/entities/SpikeTest.java
- source/core/src/test/com/csse3200/game/minigames/maze/areas/terrain/MazeGameAreaTest.java
- source/core/src/test/com/csse3200/game/minigames/maze/components/MazeCombatStatsComponentTest.java
- source/core/src/test/com/csse3200/game/minigames/snake/AppleTest.java
- source/core/src/test/com/csse3200/game/minigames/snake/SnakeGameTest.java
- source/core/src/test/com/csse3200/game/minigames/snake/SnakeGridTest.java
- source/core/src/test/com/csse3200/game/minigames/snake/SnakeTest.java
- source/core/src/test/com/csse3200/game/rendering/Minigames/GridRendererTest.java
- source/core/src/test/com/csse3200/game/rendering/Minigames/Snake/AppleRendererTest.java
- source/core/src/test/com/csse3200/game/rendering/Minigames/Snake/SnakeRendererTest.java
- source/core/src/test/com/csse3200/game/utils/SortedIntMapTest.java
Reduces code smells in tests as per sonarcloud. Increases coverage marginally in utils test, and adds game extension to a few tests.
Related to #538 
All current unit tests pass (only test files modified)
> Reduce Code Smells in Tests

- source/core/src/main/com/csse3200/game/areas/terrain/TerrainResource.java
Fixes the bug as stated in the name.
> Fix Crash after Combat Bug

- source/core/src/main/com/csse3200/game/areas/MiniMapDisplay.java
- source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
- source/core/src/main/com/csse3200/game/components/combat/quicktimeevent/QuickTimeEventDisplay.java
- source/core/src/main/com/csse3200/game/components/gameover/GameOverLoseDisplay.java
- source/core/src/main/com/csse3200/game/components/inventory/PlayerInventoryDisplay.java
- source/core/src/main/com/csse3200/game/components/mainmenu/HelpWindow.java
- source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
- source/core/src/main/com/csse3200/game/components/quests/AchievementDisplay.java
- source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenu.java
- source/core/src/main/com/csse3200/game/components/stats/StatDisplay.java
- source/core/src/main/com/csse3200/game/components/story/StoryDisplay.java
- source/core/src/main/com/csse3200/game/minigames/maze/Maze.java
As title states, this PR aims to resolve all the Reliability issues.
Checked with each file that nothing nothing had changed in game.
> [Team 2] Resolving all Reliability issues

- source/core/src/main/com/csse3200/game/areas/MiniMapDisplay.java
- source/core/src/main/com/csse3200/game/areas/combat/CombatAreaConfig.java
- source/core/src/main/com/csse3200/game/areas/forest/ForestGameArea.java
- source/core/src/main/com/csse3200/game/components/animal/AirAnimalSelectionDisplay.java
- source/core/src/main/com/csse3200/game/components/animal/LandAnimalSelectionDisplay.java
- source/core/src/main/com/csse3200/game/components/animal/WaterAnimalSelectionDisplay.java
This concludes the issue #579 which is intended to further remove code smells across the repository. 
Also fixes the bug where the bear crashes upon fighting #586 .
This PR should change NO functionality aside from the aforementioned bug.
Closes #579 
Closes/fixes #586 
Play-testing reveals no change to functionality. All unit tests pass.
> Collaborative Refactoring Out SonarCloud Smells

- source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
just a fix for inventory as skins have been modified.
Fixes / Closes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> fixed inventory

- source/core/src/main/com/csse3200/game/minigames/MiniGameConstants.java
Very minor changeed to update score thresholds as per https://github.com/UQcsse3200/2024-studio-2/wiki/Mini%E2%80%90Game-User-Testing-and-Game-Balancing and the minigame pop ups
Fixes / Closes # (issue)
#604
> Updated Score Thresholds

- source/core/src/main/com/csse3200/game/entities/configs/BaseFriendlyEntityConfig.java
Fixing bad javadoc that was causing main to fail.
> fixing javadoc so it doesn't fail

- source/core/assets/configs/defaultsaves/minigame.json
- source/core/assets/defaultsaves/player.json
- source/core/src/main/com/csse3200/game/areas/combat/CombatArea.java
- source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
- source/core/src/main/com/csse3200/game/components/animal/AnimalRouletteActions1.java
- source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
- source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
- source/core/src/main/com/csse3200/game/gamestate/data/PlayerSave.java
- source/core/src/main/com/csse3200/game/gamestate/data/WorldState.java
Cleaned up quest/save functionality and added saves for player stats (health, hunger etc)
Closes #286 
Ran game with standard save testing schema with a focus on player stats.
> cleaned up quest/save functionality and added saves for player information

- source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
- source/core/src/test/com/csse3200/game/components/tasks/GriffinTaskTest.java
- source/core/src/test/com/csse3200/game/components/tasks/KangaJoeyTaskTest.java
- source/core/src/test/com/csse3200/game/entities/factories/BossFactoryTest.java
- source/core/src/test/com/csse3200/game/entities/factories/EnemyFactoryTest.java
Minor Bug Fix fixing naming of mini game stats
> fixed statName of minigame medals.
